### ISSUE TITLE
suite a la 1.0.6

### ISSUE THREAD

**Issue by Fr-Dae** [Unitystation-fork/Unitystation-Tutorial_Standalone#109]
- [ ] 1- le numero du build en bas est toujours 3921 (inexacte)
- [X] 2- pas de son ? ( il suffisais de cocher une case dans l'interface "unmute")
- [ ] 3- la traduction allemand est partie ?
- [x] 4- en français, le bot ne parle plus  
- [x] 4b- ni en anglais
- [x] 5- il manque les gants sur la tables (nouveau soucis, on ne peux pas les prendre)
- [ ] 6- pas de CO² dans la piece toxique
- [ ] 7- ni de air controle
- [ ] 8- explorer gaz mask ne devrais pas etre présent, cela induit les joueurs en erreur
- [ ] 9- il n'y a plus de firedoor ? (ni de bouton)
- [ ] 10- pas de aircontrole
- [x] 11- le casier a oxygen a ete remplacé par un casier gris et vide
- [x] 12- toute les lampe sans exeption sont a l'envert

**Comment by juliengrima** [comment]
https://drive.google.com/drive/folders/1DPSj4Nm7J8UGQT59kAZaDmRWWSNKp3Vv?usp=drive_link

**Comment by juliengrima** [comment]
https://github.com/Unitystation-fork/Unitystation-Tutorial_Standalone/issues/133
