### ISSUE TITLE
Language files not building

### ISSUE THREAD

**Issue by ANGELB3AR** [Unitystation-fork/Unitystation-Tutorial_Standalone#110]
There are XML language files currently being stored in Unitystation-Tutorial\Tools\Languages_Files\languages.  The files must be made available to read after building, but the build does not have access to this file structure.

**Comment by Fr-Dae** [comment]
#133 
#107

**Comment by juliengrima** [comment]
https://github.com/Unitystation-fork/Unitystation-Tutorial_Standalone/issues/133

**Comment by juliengrima** [comment]
https://github.com/Unitystation-fork/Unitystation-Tutorial_Standalone/issues/133
