### ISSUE TITLE
les dialogue francais ne se lance pas. cliquer sur le bot ne fait rien.

### ISSUE THREAD

**Issue by Fr-Dae** [Unitystation-fork/Unitystation-Tutorial_Standalone#133]

**Comment by Fr-Dae** [comment]
https://github.com/Unitystation-fork/Unitystation-Tutorial_Standalone/issues/110
https://github.com/Unitystation-fork/Unitystation-Tutorial_Standalone/issues/107

**Comment by juliengrima** [comment]
In #18  Hors ligne : New Offline Button and force Offline at start in Manager Script.

Creatiing for new branch with merge #18  Hors ligne to 133# Dialogue => #133
Creating Prefab Tutorial and add this to Tuto_Bot.Cs / TutoBot.prefab
research  Lang_bot.cs and fixed path "languages/Lang_Bot_" + GameManager.Instance.language+".xml")  => 
"StreamingAssets/languages/Lang_Bot_" + GameManager.Instance.language+".xml")

Please build and test in Windows

**Comment by juliengrima** [comment]
le dialogue Français s'affiche
