### ISSUE TITLE
rendre la station moins propre et plus a l'abandon

### ISSUE THREAD

**Issue by Fr-Dae** [Unitystation-fork/Unitystation-Tutorial_Standalone#14]

**Comment by HenriquePEIXRIB** [comment]
https://github.com/Unitystation-fork/UnityStation-Tutorial_module/tree/HenriquePEIXRIB-patch-1

https://imgur.com/0KxMBoS

**Comment by Fr-Dae** [comment]
![number.png](https://app.gitkraken.com/api/glo/boards/637e8e75d813e50b79df7f8a/attachments/637f60a64bcc84004e3eb2ce)
![0KxMBoS.png](https://app.gitkraken.com/api/glo/boards/637e8e75d813e50b79df7f8a/attachments/637f60b84bcc84004e3eb2d0)

**Comment by Fr-Dae** [comment]
utilise plutot de petite touche de rouille, de crasse ou de dommage, plutot que tous repeindre.

pour les tuile , utilise plutot les graffiti 

la salle 1 et medical doivent etre propre.

**Comment by mortifia** [comment]
les ressources dans le ticket sont en 404 @Fr-Dae

**Comment by Fr-Dae** [comment]
![0KxMBoS](https://user-images.githubusercontent.com/23202421/207055711-5f28a824-94dc-49fe-9421-e23d2d6b609a.png)
![number](https://user-images.githubusercontent.com/23202421/207055716-ea290a1a-4d61-463f-975d-590837161462.png)
